### ISSUE TITLE
Incorporate reference links into appropriate Twine pages

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#10]
I've read through the Word docs for the various demos and didn't see any listed reference links. There are several pages that I'd consider somewhat "authoritative" (if such a thing exists in Wikidata) that provide some consensus views about what properties should be provided for various item types. For reference, we should probably put links to them on the appropriate pages when we create them. Here are some:

- [WikiProject Books](https://www.wikidata.org/wiki/Wikidata:WikiProject_Books) briefly explains FRBR and its use in Wikidata
- [WikiProject Periodicals](https://www.wikidata.org/wiki/Wikidata:WikiProject_Periodicals) separates out metadata properties for periodicals, organization, volume, issue, and article.
- [Describing people (Stanford)](https://www.wikidata.org/wiki/Wikidata:WikiProject_Stanford_Libraries/Describing_people) includes recommended properties

**Comment by CliffordAnderson** [comment]
Yes, great suggestions. Would it be self-serving to include some of our own [reference materials](https://www.wikidata.org/wiki/Wikidata:WikiProject_VandyCite/training-materials) too? Of course, we'd have to build them out a little more substantially.

**Comment by baskaufs** [comment]
I have decided to try to create these along with the TLDR text, which I'm managing in the `learning-objectives.docx` document in the root Box folder.
