### ISSUE TITLE
Test reference links in iFrames to see how they look

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#11]
Create a test page that contains iFrames for various external websites to which we would refer users. Needs a list of URLs

**Comment by cylew** [comment]
Hi Steve,

Following are the three links embedded in the Journal Article tutorial.

Retrieving DOI for journal article from CrossRef.org (metadata search)
https://search.crossref.org/?from_ui=yes&q=metadata
Retrieving PubMed ID
https://pubmed.ncbi.nlm.nih.gov/
Retrieving PMC ID
https://europepmc.org/

Let me know if you have questions about this.

Thanks,
CHarlotte

**Comment by baskaufs** [comment]
Great, thanks @cylew !

**Comment by baskaufs** [comment]
@cylew Here is the [test page](https://heardlibrary.github.io/twine-for-wikicite/iframe.html) so you can see how it looks. Only one of the three websites works in an iFrame (the PMC ID one). I'm not sure why. All three links all are fine if you just open them in another tab.
