### ISSUE TITLE
Investigate capabilities of Twine for tracking progress

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#12]
Investigate the internal capabilities for checking what pages have already been visited, and other "game-type" features such as tracking points, etc. How hard would they be to implement and if they are feasible to use, are they actually useful in our situation?

**Comment by CliffordAnderson** [comment]
Is [this](https://www.motoslave.net/sugarcube/2/docs/#twinescript-variables) what you have in mind, Steve?

**Comment by baskaufs** [comment]
Try [this](https://heardlibrary.github.io/twine-for-wikicite/sugarcube_macros.html).

**Comment by baskaufs** [comment]
A sugarcube reference:

https://www.motoslave.net/sugarcube/2/docs/

**Comment by baskaufs** [comment]
Not exactly related, but a link for how to incorporated image maps in a Twine story

http://twinery.org/questions/26609/sugarcube-clickable-image-that-links-other-sections-story
