### ISSUE TITLE
Find out about cloud capabilities of the Adobe suite

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#20]
We have been assuming that we would use Box, but if there is an easier to use cloud capability built-in, we should maybe use that.

**Comment by baskaufs** [comment]
We apparently have 100 GB of cloud storage available. In an application such as Photoshop, you can use the Save As dialog to save somewhere in your Creative Cloud. To share it via a link:

Open Creative Cloud

![adobe-cloud](https://user-images.githubusercontent.com/5765781/106927133-7d3bb980-66d7-11eb-8cc6-51284ae2c2c7.png)

Click on the `Your work` tab, then the `Cloud documents` icon at the left. Click on the folder to open, then the file.

![adobe-share](https://user-images.githubusercontent.com/5765781/106928047-647fd380-66d8-11eb-9635-c680d486ea59.png)

With the document selected, click the `Share` icon on the right, then select `Get link`.

![adobe-link](https://user-images.githubusercontent.com/5765781/106928526-e3750c00-66d8-11eb-8b7c-23b03c579b9b.png)

In the popup, click `Copy Link`. Paste the link into an email or message and send to the person you want to share with.

----
There is also an option to `Share...` in the Photoshop File menu, but I think it actually just sends the file via Messenger or Airdrop (not the cloud). But haven't tried it.

**Comment by baskaufs** [comment]
There is a second feature called "libraries" that can be shared with others. However, I cannot figure out in Photoshop or from Cloud Documents how to actually put a document into the shared library.

**Comment by baskaufs** [comment]
Creative Cloud has an application called Bridge

![Untitled 2](https://user-images.githubusercontent.com/5765781/107216327-3baa5780-69d2-11eb-9b4b-3308e18506c0.png)

You can access libraries there

![Untitled](https://user-images.githubusercontent.com/5765781/107216700-bd9a8080-69d2-11eb-959c-2cfb24d9b878.png)

Drag and drop is enabled for libraries.

![Untitled](https://user-images.githubusercontent.com/5765781/107216807-e589e400-69d2-11eb-9790-115d29c27576.png)

This is supposedly drag and drop but it doesn't work and I can't find any place in Premiere to enable libraries.

**Comment by baskaufs** [comment]
Inside Premiere, there seems to be a way to add members to a team project. I added Andy and Cliff to the team. Can't remember how. Maybe under File?

For whatever reason, there is now a Libraries tab and the video I added there is now showing up!


![Untitled](https://user-images.githubusercontent.com/5765781/107220380-e40eea80-69d7-11eb-8dbc-57f41122bd91.png)

I tried adding the video from the Library to the project and that worked. But I'm not sure what other collaborators will see.

@CliffordAnderson @awesolek2 I think maybe we need to Teams/Zoom live to find out what collaborators can see and do. I have invited both of you to collaborate on this project, did you see the invitation? I also added Andy to the Library (Cliff already is sharing it.

**Comment by CliffordAnderson** [comment]
@baskaufs @awesolek2 I can see the shared library, but I cannot find Andy's character animator project there. I think this would be good to discuss at both meetings today.

**Comment by CliffordAnderson** [comment]
@baskaufs I think you made your library read only. I found Andy's files on Teams, but I cannot add  them to Creative Cloud.

**Comment by baskaufs** [comment]
@CliffordAnderson When I created the library (and I just tried again), I was only given an opportunity to set the name - no permissions. Once created, I only could add collaborators with two settings: edit or view. Right clicking did nothing and I could see no relevant menu items. 

A Google search came up with some [info about permissions](https://helpx.adobe.com/adobe-connect/using/user-guide.html/adobe-connect/using/setting-permissions-library-files-folders.ug.html) but it seemed to require a more complex setup than we have involving [groups](https://helpx.adobe.com/adobe-connect/using/setting-permissions-library-files-folders.ug.html#libraries) which need to be managed using [Adobe Connect Central](https://helpx.adobe.com/adobe-connect/using/users-groups.ug.html#add_or_remove_group_members) an application that I don't think is included in our subscription.

I will look at the videos for more wisdom, but so far, so bad.

**Comment by baskaufs** [comment]
I was able to add @awesolek2 's video to my project, but the right half of the robot was cut off. I couldn't see how to expand the format to wider screen, although I suppose there is a way. 

![image](https://user-images.githubusercontent.com/5765781/107712181-98d23180-6c8e-11eb-8971-9c8a799e191f.png)

**Comment by baskaufs** [comment]
OK, so it appears that we are successfully using Bridge for the raw materials. So I'm closing this.
