### ISSUE TITLE
Proofread/correct multilingual hyperlink text

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#28]
@cylew @Talinum Currently, I have generated the hyperlink and navigation text in non-English languages by pasting text into Google Translate and guessing how to put it into the link text.

The links need to be looked at by a native speaker to figure out how they would typically be rendered in the target language. I am going to create a doc with the existing text. If you can please edit it to the correct text and then ping me by commenting here that would be great. I will correct the Twine and let you proofread it again after the changes have been made.

Here is the document with the text to be edited:

<https://vanderbilt365.sharepoint.com/:w:/s/Libraries/libgrps/DiSC/Ee_wAVeO4LxMhyKJQbl9MI4B0q-_JTWcWlvPETev1U2qJA?e=lInurH>

There is other non-link text in the Twine, but let's not bother fixing it until we decide for sure what explanatory text should go in each passage.

- [x] Greg: Spanish [View existing document in Spanish](https://heardlibrary.github.io/twine-for-wikicite/?es)
- [x] Charlotte: simplified Chinese [View existing document in simplified Chinese](https://heardlibrary.github.io/twine-for-wikicite/?zh-Hans)

**Comment by Talinum** [comment]
Hi Steve,
    I edited the nav links and below is the non-link edited.

Aquí aprenderás a crear y editar ítems. Elije dónde te gustaría comenzar.

Greg

**Comment by baskaufs** [comment]
OK, @Talinum @cylew I have made the changes to the link text. Try visiting the correct language link at [the GitHub repo landing page](https://github.com/HeardLibrary/twine-for-wikicite) and see if it looks right. After you verify, I'll close this issue.
