### ISSUE TITLE
Do we worry about subtitles in languages other than English?

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#29]
When I provide the script text for English videos, the subtitling/captioning is really great. 

For Spanish, here are the subtitling options:
![image](https://user-images.githubusercontent.com/5765781/110153637-f1d24880-7da8-11eb-8e34-82ce3b82b195.png)
I think the Upload file option for a text file with no timings is an option as long as the text is in the original video language.

Another question? Should we characterize the Spanish as "Latin American" or something else? I think the other options are "Spain", "Mexico", "US", and generic. 

Automatic subtitling is not available for Chinese but I think with an uploaded script it will match them to the video. I would need to have a cleaned up script that matches the video exactly since I can't clean it up myself as I do for the English.

**Comment by Talinum** [comment]
I think it is OK to call it generic Spanish.

**Comment by baskaufs** [comment]
@Talinum feels we can use generic Spanish.
