### ISSUE TITLE
Check the Chinese title as entered in the YouTube video

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#30]
Each video is required when uploaded to have a title. I just ran the English title through Google Translate to get something. Here it is:
English: Editing a journal article item
编辑期刊文章项目

Similarly, there is a description to add -- I think it helps people to search, although it does not show up anywhere obvious when viewing the video. Here is what I used, again from Google Translate:
English: Demonstration showing how to edit a Wikidata item for a journal article.
演示显示如何编辑期刊文章的Wikidata项目。

As a part of our workflow, we need to provide a title and description like this in each language for every video. Let's just put it as the first two lines, separated by a space, at the top of the captioning document. I can pull them out when I upload the videos and separate out the captioning text.

When we've got the workflow straightened out (and any corrections to the Chinese above), we can close this.

**Comment by cylew** [comment]
Steve，
I've revised the second Chinese sentence in your message, and please have it replaced as follows.
演示如何编辑期刊文章的项目。
Thanks,
Charlotte

**Comment by cylew** [comment]
Steve,

I logged in to GitHub and left a comment on the Chinese introduction.
Let me know if you receive it. Would you rather to retrieve my Chinese correction(s) from the email or in GitHub. Please advise.

Thanks,
Charlotte

**Comment by baskaufs** [comment]
@cylew Fixed YouTube video description for Chinese version of article video.
