### ISSUE TITLE
01 Book Concept

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#31]

**Comment by baskaufs** [comment]
Status March 11: 
Chinese video complete, on YouTube, and embedded in Twine
English video complete, on YouTube, and embedded in Twine.
Spanish script in Box

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish book animation uploaded to Box

**Comment by CliffordAnderson** [comment]
@awesolek2 Chinese CA still not importing because of broken references :(

**Comment by CliffordAnderson** [comment]
@awesolek2 No luck with Spanish either.
![Screen Shot 2021-03-24 at 1 21 09 PM](https://user-images.githubusercontent.com/1919466/112363778-df5e7700-8ca3-11eb-811f-3eee9096b934.png)

**Comment by CliffordAnderson** [comment]
Ah, sorry @awesolek2, I think I identified the problem on my end. Looks like it will work after all.

**Comment by CliffordAnderson** [comment]
@cylew The Chinese video is completed and uploaded.

**Comment by CliffordAnderson** [comment]
@baskaufs Videos for English, Spanish, and Chinese all ready for posting to YouTube

**Comment by baskaufs** [comment]
Complete

**Comment by awesolek2** [comment]
@CliffordAnderson French version animated
