### ISSUE TITLE
02 Article concept

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#32]

**Comment by baskaufs** [comment]
Chinese video complete, on YouTube, and embedded in Twine
English video complete, on YouTube, and embedded in Twine.
Spanish script in Box

**Comment by baskaufs** [comment]
AFAIK, this video still has the problem that the TN Library Association isn't really the journal, it's the publisher. I think we were going to fix this and eventually re-do the videos.

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish article animation now in Box

**Comment by CliffordAnderson** [comment]
@baskaufs I guess we are not fixing these videos, at least for the present. So Chinese, English, and Spanish ready to be posted, @baskaufs. Let's talk about revising them sometime toward the end of the project, if we have time.

**Comment by baskaufs** [comment]
Trying to force YouTube to redo the Spanish subtitles in UTF-8 to get rid of stupid weird characters, but otherwise this is done.
