### ISSUE TITLE
03 Author concept

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#33]

**Comment by baskaufs** [comment]
March 11 status
English needs video production
Chinese needs video prod.
Spanish script being finished

**Comment by baskaufs** [comment]
@cylew @Talinum Was this video (03 Author) the one that was too long? Should I try to break it up or are we already too far into production to do that?

**Comment by cylew** [comment]
Steve,

I checked the length of the Chinese recording, it's  around 3 minutes 50 seconds. If it's under five minutes, I humbly think we don't need to break it up.

Charlotte

**Comment by baskaufs** [comment]
OK, good to know. I don't really want to disrupt work that has already been done.

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish version now animated. There is a bit of dead air at the beginning that I filled with "waving." I did it at a couple of points so you could pick one that works best as an intro. Feel free to cut the rest.

**Comment by CliffordAnderson** [comment]
@awesolek2 The CA track cuts out about fifteen seconds before the end of the audio/Loom video. I wonder if that's related to the dead air issue. Would you please check?

**Comment by awesolek2** [comment]
@CliffordAnderson Looks like a mistake on my end. I'll reanimate now.

**Comment by CliffordAnderson** [comment]
@awesolek2, Cool, thanks!

**Comment by awesolek2** [comment]
@CliffordAnderson Done. Uploaded as Spanish_Authors_2

**Comment by CliffordAnderson** [comment]
@awesolek2 Great, the new CA worked perfectly. @baskaufs, the Chinese, English, and Spanish videos are ready for the web.

**Comment by baskaufs** [comment]
The author passage has been added to the website.
