### ISSUE TITLE
04 Item concept

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#34]

**Comment by baskaufs** [comment]
March 11
English needs video production
Chinese needs video prod
Spanish script posted needs audio recording

**Comment by CliffordAnderson** [comment]
@awesolek2 The Chinese character animator video is not importing. Can you check to see why? Thanks!
![Screen Shot 2021-03-18 at 2 49 34 PM](https://user-images.githubusercontent.com/1919466/111689035-843b0900-87f9-11eb-9641-a11f1340027d.png)

**Comment by awesolek2** [comment]
@CliffordAnderson Replaced the character animator files in Box. They should work this time (fingers crossed)!

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish Item now animated

**Comment by CliffordAnderson** [comment]
@CliffordAnderson I produced the videos for English and Chinese, but something seems wrong with the CA for Spanish, which will not load. Would you please take a look? Thanks!

**Comment by awesolek2** [comment]
@CliffordAnderson I was afraid of that. Box timed out several times before the project could be totally loaded, but I thought I had it worked out. I'm going to try an experiment and zip it locally and upload the zipped file.

**Comment by CliffordAnderson** [comment]
<img width="826" alt="Screen Shot 2021-04-01 at 2 32 00 PM" src="https://user-images.githubusercontent.com/1919466/113344782-262d1c00-92f7-11eb-83ad-4ae85bb40313.png">

Still getting an error. I think there's something corrupted inside of the CA file. See the screenshot above. Could you perhaps send me a rendered version (i.e. mp4 file)?

**Comment by awesolek2** [comment]
Head not found! That sounds serious. Pretty sure Robbie needs one of those. Yes, I'll render it as an MP4 now.

**Comment by CliffordAnderson** [comment]
Thanks, Andy. Here a little more about the [error](https://community.adobe.com/t5/character-animator/project-won-t-open-libgit2-error-3-9-object-not-found-no-match-for-id/m-p/10423823). Seems like you could fix it by deleting the file they mention. If you do create the MP4, remember to use Alpha to preserve the transparency. Sorry for all the trouble!

**Comment by awesolek2** [comment]
Got it! I'm heading into a 3:00 now, but I'll take a look if I get a chance before 4:00. In the interim, I uploaded a different version (simple Spanish_Item) so you might see if that one works.

**Comment by CliffordAnderson** [comment]
@awesolek2 I've upload the Spanish video, but I worry that the audio may be out of sync. At any rate, Chinese, English, and Spanish should be ready to go, @baskaufs.

**Comment by baskaufs** [comment]
The add item passage has been added to the website.
