### ISSUE TITLE
05 Person Concept

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#35]

**Comment by baskaufs** [comment]
Status on March 11:
Engilsh initial script done, needs to be finalized
Spanish done may need revisions after being finalized
Chinese

**Comment by baskaufs** [comment]
@awesolek2 @cylew @Talinum Revisions on script 05 Person Concept are done.

**Comment by cylew** [comment]
I just uploaded the Chinese script on Person to Box.

**Comment by awesolek2** [comment]
English Person Animations Complete @CliffordAnderson

**Comment by CliffordAnderson** [comment]
@awesolek2, Got it! Thanks!

**Comment by CliffordAnderson** [comment]
@baskaufs the English-language video is ready to be added to Twine

**Comment by baskaufs** [comment]
Video is in the [Twine](https://heardlibrary.github.io/twine-for-wikicite/?en). Note that the TLDR text is now implemented in all of the English passages that have videos.

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese person now animated

**Comment by CliffordAnderson** [comment]
@awesolek2 There is a problem with the Spanish video. The Loom video continues significantly past the end of the mp3 track/animation. Would you please doublecheck?

**Comment by awesolek2** [comment]
@CliffordAnderson The audio file itself is substantially shorter than the mp4. So, I think there may be some pausing in the audio that is not reflected in the MP4. I can extract an audio file from the mp4 itself, but the sound quality will be sub-par because it is generated from the built-in mic. 
At the meeting this afternoon, I'll walk Greg through using the Zoom Mic as an aux input rather than creating a second audio file. That way, the quality audio will be built into the MP4 itself. I can then extract it as a WAV file in Audition. That should eliminate the syncing issues.

**Comment by awesolek2** [comment]
Addendum: In the interim, our choice here is for me to extract the existing audio from the MP4 and animate based on that. Or re-record the MP$ using the Zoom as an external mic.

**Comment by CliffordAnderson** [comment]
Thanks for the clarification, Andy. Let's try to use the MP4's audio track. I'd like to keep making progress to avoid falling behind. If we have time, we can circle back and add better audio.

**Comment by CliffordAnderson** [comment]
@baskaufs English and Chinese videos are ready.

**Comment by awesolek2** [comment]
@CliffordAnderson Sounds good, Cliff. I've got lunch cooking now, but I'll reanimate with the MP4 audio shortly.

**Comment by awesolek2** [comment]
@CliffordAnderson uploaded as "Spanish_Person_2".

**Comment by CliffordAnderson** [comment]
@baskaufs Spanish video completed. It probably could have used editing since it features some unneccessary clicking. But let's go with it for now.

**Comment by baskaufs** [comment]
Lesson 5 videos are uploaded and added to Twine. See the links from the [Landing page](https://github.com/HeardLibrary/twine-for-wikicite) to view.
