### ISSUE TITLE
06 Supporting edits

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#36]

**Comment by baskaufs** [comment]
March 11: 
English initial script done, needs to be finalized
Chinese 
Spanish

**Comment by baskaufs** [comment]
@cylew @Talinum Please take another look at the script for video 06. I have morphed it from "references" to more broadly linking an item using the full text URL and various identifier properties. I am planning to create a second script following this to include editing a bona fide reference for a statement.

**Comment by cylew** [comment]
Have we reached a consensus to postpone the script of adding references?

**Comment by baskaufs** [comment]
Well, I sort of did that. What Marymae wrote wasn't actually about references, which is why I morphed it into "supporting edits" instead of "reference concept". So 06 now is not about references, but just other kinds of statements we could make about written works. If we don't use that, then we need a different topic for 06 immediately, since it was supposed to be for this week. 

What I was proposing was to do references for 07 (since it kind of follows up on 06) but I haven't actually written it yet, so I could still push it off later and do something else.

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish Supporting Edits now animated

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese supporting edits now animated

**Comment by awesolek2** [comment]
@CliffordAnderson English mp4, wav, and animation uploaded to Box.

**Comment by CliffordAnderson** [comment]
@baskaufs Chinese, English, Spanish videos ready

**Comment by baskaufs** [comment]
@CliffordAnderson @cylew @awesolek2 @Talinum  For some reason, "06 Supporting edits" videos in Spanish and Chinese in Box do not have any sound when I try to play them using QuickTime. That is not the case with the English video, nor any of the 07 Reference videos of any language. 

I don't really have another player configured to use for testing nor have I tried uploading them to YouTube. But could someone please test whether they have sound for you? I don't want to process them further until I can verify that they actually have sound.

**Comment by CliffordAnderson** [comment]
@baskaufs Thanks for letting me know. I may need to reexport them from Premiere Pro. I'll try that later this afternoon.

**Comment by CliffordAnderson** [comment]
@baskaufs I fixed both the Chinese and Spanish videos. Sorry for the trouble.

**Comment by baskaufs** [comment]
Thanks, @CliffordAnderson. The Twine is now updated with the videos.

**Comment by marjans74** [comment]
In the Video the property Reference URL is shown. When the reference URL is added to the value field the dialogue refers to the URL as a property, rather than a value.  Need to double-check this.

**Comment by awesolek2** [comment]
@CliffordAnderson See above. Is it possible to superimpose a correction on the final video? Thanks, @marjans74

**Comment by CliffordAnderson** [comment]
I think we'd have to redo the screencast. If it stays in sync with the audio, then I can make another version of the video without much effort.

**Comment by CliffordAnderson** [comment]
@baskaufs I've edited the video per @awesolek2's suggestion. I believe it's ready to be reposted.

**Comment by baskaufs** [comment]
reposted and embed code changed in Twine
