### ISSUE TITLE
07 Adding a reference

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#37]

**Comment by baskaufs** [comment]
I'm pushing this topic off in order to move directly into adding a reference, a topic that follows more directly from the revised script for video 06.

**Comment by baskaufs** [comment]
@HeardLibrary/wikicite The English script for `07 Adding a reference` is ready for review in `Script` subfolder in Box.

**Comment by awesolek2** [comment]
English Reference Animation Complete @CliffordAnderson

**Comment by baskaufs** [comment]
@Talinum @cylew I don't think you ever got pinged on this, but there were no changes to script 07, so it is finalized.

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese Reference Animation complete

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish reference animation complete

**Comment by CliffordAnderson** [comment]
@baskaufs Chinese, English, and Spanish videos are completed and on Box

**Comment by baskaufs** [comment]
@CliffordAnderson @awesolek2 @cylew @Talinum @marjans74 The 07 adding reference videos (and 06) are embedded in the Twine now in all languages so you can look at them now from the appropriate language link on the [GitHub landing page](https://github.com/HeardLibrary/twine-for-wikicite).
