### ISSUE TITLE
08 Set up account/log in

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#38]

**Comment by baskaufs** [comment]
@CliffordAnderson @cylew @Talinum @awesolek2 The English script for `08 Set up account/log in` has been placed in the `scripts` subfolder in Box. It's ready for review and discussion at our next meeting on Thursday. 

Please note that with each script I've been creating "Too long, didn't read" (actually "didn't watch", but that doesn't work with TLDR) text to go on the Twine passage page along with the embedded video. I don't think we ever actually discussed whether this is what we wanted on the page, but we've got to get this horse moving, so I decided to move forward with this in lieu of any better ideas. We also should probably include some reference links on the pages, but I haven't put any thoughts into what the links should be and which passages they belong in yet. 

So unless we decide not to use the TLDR bullet points I've written, they will have to be translated along with the script. The `learning-objectives.docx` file in the root folder of Box is where the TLDR text is written. There are slots for the es and zh-hans translations in that doc, so you can just paste them in there and I'll grab them from that doc when I put them in the Twine. We can also slot in any reference links under the appropriate videos when we decide on them.

**Comment by baskaufs** [comment]
@cylew @Talinum @awesolek2 Script 08 is finalized with only a minor change

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese animation complete.

**Comment by awesolek2** [comment]
@CliffordAnderson English animation complete. There are a couple of auto-generated password popups. I am not using a PW key with my account, so I don't think this is a security concern, but let me know if you think otherwise. We can try to rerecord, or maybe they can be blurred out in video production?

**Comment by CliffordAnderson** [comment]
Will take a look, @awesolek2 If I see an issue, I can try the blurring out approach.

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish account animated

**Comment by CliffordAnderson** [comment]
@baskaufs Videos for English, Chinese, and Spanish now available on Box

**Comment by baskaufs** [comment]
The video for setting up an account has been added to the Twine as a passage at the start of the story. We probably will need to think about how the navigation should be set up for that part of the story, but for now it is there.
