### ISSUE TITLE
Can't create a team because people aren't members of our "organization"

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#39]
@CliffordAnderson I created a team called "WikiCite" but could only add you to it because the other people in the project aren't "members" of the "HeardLibrary" organization. Would it be problematic to add them to the organization? That way, when I want to tell everyone that the next script is ready for review, I could @ mention @HeardLibrary/wikicite instead of having to type all of the names separately.

**Comment by baskaufs** [comment]
I don't think I can add them to the organization, since I'm not an admin, right?

**Comment by CliffordAnderson** [comment]
@jgambill has been cleaning up members of the organization to reduce our billing overhead. @jgambill, could you help @baskaufs figure out the best way to connect the members of our WikiCite grant project so that we can ping everyone easily? Thanks!

**Comment by jgambill** [comment]
Sure @CliffordAnderson, happy to help.

@baskaufs how many more people are you needing to add to your team?

**Comment by baskaufs** [comment]
Hmmm. I didn't know it cost more to have people be members. I just wanted to create a team with @Talinum @cylew @awesolek2  @marjans74 plus @CliffordAnderson and me who are already on the @HeardLibrary/wikicite team I created. It's not that critical -- just is a way to avoid having to type all of their names to ping them.

**Comment by CliffordAnderson** [comment]
If we add them as external collaborators, will that work?

**Comment by jgambill** [comment]
Andy is already in the org. The others are already outside collaborators. Only org members can be on teams, though. Charlotte occupies one of our seats so I could add her to the org without paying. We would have to purchase two more licenses to add the remaining two users to the org, though. Licenses are $48/yr per user. I was generally thinking the org would be reserved for library staff, but that is not a hard and fast rule by any means.

**Comment by jgambill** [comment]
An alternative to adding them to the org could be to tell them to watch the repo and set their desired notification level. That doesn't allow you to explicitly ping them like you can with org teams, though.

**Comment by poulterd** [comment]
Jodie,

Let’s add this to our agenda Wednesday

**Comment by baskaufs** [comment]
Well, they are all library staff. But it definitely isn't important enough to pay $48 per year just so I don't have to type a few extra characters.

**Comment by jgambill** [comment]
@baskaufs Could you let me know who the other accounts belong to? I didn't know they were library staff.

**Comment by baskaufs** [comment]
@Talinum is Greg Weldy and @marjans74 is Marymae Jansson. The "team" are the people that are working on our Wikicite grant project. Marymae is scaling back her participation, though, so it isn't entirely clear whether to still include her or not. I was just including her by default.

**Comment by jgambill** [comment]
Thanks Steve!

**Comment by jgambill** [comment]
It sounds like we are okay to not make any user changes at this time. Dale and I are working on spelling out some guidelines for who should be in the org vs. who should be an outside collaborator (knowing there will be exceptions sometimes) so we can address this kind of question more clearly in the future.
