### ISSUE TITLE
Create a character rig for Adobe Character Animator

### ISSUE THREAD

**Issue by CliffordAnderson** [HeardLibrary/twine-for-wikicite#4]

**Comment by awesolek2** [comment]
I initially thought I could rig a puppet and to that end, watched a few tutorials and experimented a bit. I think this is within the realm of possibility for me, but likely not within the project's deadlines. So, I explored outsourcing on Fivrr. There are a huge number of contractors willing to rig puppets for less than $100. For additional fees, some will add the puppet to a provided video and synch it with narration. Questions:
I can select and contact a vendor to discuss options, but I will likely need to know:
--Our budget for this
--Any preferences we have in design (male/female human? Imaginary character? etc)

**Comment by awesolek2** [comment]
Selected vendor on Fivrr. Awaiting response.
