### ISSUE TITLE
10 Qualifiers

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#41]
Mention series ordinal if already introduced. Illustrate with start time and end time for either publisher or a person whose affiliation changes.

**Comment by baskaufs** [comment]
@CliffordAnderson @awesolek2 @Talinum @cylew The qualifiers script is now uploaded into Box. There are a few questions I have about it, but we can discuss at the meeting.

**Comment by baskaufs** [comment]
@cylew @awesolek2 @Talinum  The qualifiers script 10 is finalized.

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese identifiers animated

**Comment by awesolek2** [comment]
@CliffordAnderson English audio, video, and animation in Box

**Comment by CliffordAnderson** [comment]
@awesolek2 We are missing the CA for Spanish, I think.

**Comment by CliffordAnderson** [comment]
@baskaufs English and Chinese videos ready for posting.

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish animation uploaded

**Comment by CliffordAnderson** [comment]
@awesolek2 Got it! @baskaufs Spanish version ready for uploading.

**Comment by baskaufs** [comment]
Videos for 19 Qualifiers uploaded and embedded into the Twine for all three languages. To wrap up this one, we need es and zh TLDR text and zh description (for YouTube).

**Comment by baskaufs** [comment]
Finished, cover metadata issues separately
