### ISSUE TITLE
Short titles and descriptions needed for most existing videos

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#43]
@Talinum @cylew @awesolek2 @CliffordAnderson 

In the `learning-objectives.docx` document in the root folder of our shared Box folder I have added spaces for making translations of short titles and descriptions to be used with the YouTube videos and to be added to the starting sequence when Cliff assembles the final video.

I've put the existing titles and descriptions in the doc and also created ones for English for the rest of the videos. We'll need to go back and provide the missing ones for the existing videos and make titles and descriptions for the new videos as they are produced.

**Comment by baskaufs** [comment]
Nearly all videos now have these. There aren't descriptions for most Chinese videos, but that doesn't matter until the videos are made public on YouTube since that is the only place they will be seen. Still missing:

"6 Supporting your edits" does not have a Chinese title. It has this description: "支援你所编辑的数据" in the learning-objectives.docs file. @cylew Is that actually a misplaced title?

Actually, I think that is the only missing one.

**Comment by cylew** [comment]
Sorry, the title has been misplaced. Yes, the title is 支援你所编辑的数据.
Thanks for catching this.
