### ISSUE TITLE
11 Titles

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#44]
Created box folder and entry in learning objectives document.

**Comment by baskaufs** [comment]
@Talinum @awesolek2 @cylew @CliffordAnderson @marjans74 The script for 11 Titles is ready for review. Still working on 12.

**Comment by baskaufs** [comment]
The English script for 11 Titles is finalized

**Comment by awesolek2** [comment]
@CliffordAnderson English video, audio, and animation uploaded to Box.

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese animation uploaded to Box

**Comment by CliffordAnderson** [comment]
@baskaufs English and Chinese videos are ready. @Talinum @awesolek2 Spanish version is missing.

**Comment by baskaufs** [comment]
Videos for 11 Titles have been uploaded and embedded for English and Chinese. Missing Spanish video, missing TLDR for Spanish and Chinese, missing Chinese description for YouTube.

**Comment by baskaufs** [comment]
Actually, 10, 11 and some others don't have Chinese titles on YouTube. That's actually more important than the descriptions because it actually shows up in the corner of the embedded video when the page loads and the description doesn't really show up anywhere.

**Comment by baskaufs** [comment]
Still missing Spanish video for 11 Titles

**Comment by Talinum** [comment]
I can see the Spanish video for 11 titles in the Box web interface, and it plays. @baskaufs

**Comment by baskaufs** [comment]
OK, I see the problem. The video was in the "Spanish" folder instead of the "Video" folder like the other ones, so I didn't think of looking there. So we should be good here!

**Comment by baskaufs** [comment]
@CliffordAnderson @Talinum OK, I retract that. The video in the Spanish folder doesn't have the introductory stuff, background music, etc. I'm still only seeing completed Chinese and English in the "Video" folder (in either the web interface or synch). Am I still looking in the wrong place???

**Comment by awesolek2** [comment]
Apologies for the confusion on this one! @CliffordAnderson Spanish version now animated.

**Comment by CliffordAnderson** [comment]
No problem, @awesolek2 @baskaufs Spanish video ready

**Comment by baskaufs** [comment]
11 Titles: Spanish embed code added
