### ISSUE TITLE
17 Classification

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#45]
Created Box folders and entry in learning objectives document

**Comment by baskaufs** [comment]
Morph this using something like OCLC subjects for journals (look at peer institution catalogs). WorldCat or LC are open access.

**Comment by baskaufs** [comment]
Created Box folder and stub script

**Comment by baskaufs** [comment]
Changed name from "subject" to "classification" since I think we should talk about "genre" in addition to "main subject".

**Comment by baskaufs** [comment]
@CliffordAnderson @marjans74 @cylew @awesolek2 @Talinum I have created a draft script for video 17 and put it into Box. As anticipated, I struggled with it and didn't start on it until after I did some querying to try to understand the landscape for "main subject". It is clear that use of main subject is very inconsistent. When looking at the property page for main subject, I noticed that it clarified how that property was different from "genre". Genre is actually used more consistently than main subject, so I decided to include it in the script since I think in some ways it's as useful or more useful than main subject. That's why the title of the script morphed from "subject" to "classification".

The script doesn't actually have a working example of adding values for the properties -- it just examines how the terms are used in a couple examples.  I think that is OK at this point in the series since they've already added values a bunch of times. If I were to add an example of adding a value, it would probably make the video too long and something else would have to be cut out. 

Take a look at the script when you have time and if you have strong opinions right away, put them in the comments here and I can try to do a revision prior to our meeting this week. Otherwise, I guess we can just talk about it then.

**Comment by baskaufs** [comment]
Oh, no. I forgot to notice @Talinum's email suggesting that we cover P101 (field of work) for people and organizations in this lesson. I think that would be an appropriate additions and probably more useful actually than main subject and genre. But I'll have to cut something out to put that in. So think about that as you look at the draft.

**Comment by baskaufs** [comment]
At our meeting this week, we decided to skip P101 (field of work) since we are already covering a lot. 

I just read through @Talinum's additions to the script and they seem like a good addition. Unless there are objections, I think we can consider the script for 17 to be finalized.

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish version animated

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese version animated. I gave this one a few attempts because it is having a lot of trouble tracking my eyes. It's imperfect, but it'll have to do!

**Comment by awesolek2** [comment]
@CliffordAnderson English version recorded and uploaded

**Comment by CliffordAnderson** [comment]
@baskaufs Chinese, English, and Spanish videos are ready

**Comment by baskaufs** [comment]
Videos uploaded and embedded for 17 Classification
