### ISSUE TITLE
12 Gadgets

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#46]
renamed folder 12 to gadgets

**Comment by baskaufs** [comment]
@awesolek2 @CliffordAnderson @Talinum @marjans74 @cylew The English script for "12 Gadgets" is in the Box folder. 

I had to bail on the Subject Analysis lesson, so I substituted the first Gadget lesson. We definitely want to cover gadgets and I'm not feeling well, so I just picked that one because it was easy to do. We can talk about the Subject Analysis lesson at the meeting tomorrow.

**Comment by baskaufs** [comment]
The script for 12 Gadgets is finalized

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese Gadgets Animated (that actually sounds kind of fun!)

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish gadgets animated

**Comment by awesolek2** [comment]
@CliffordAnderson English version recorded and animated

**Comment by CliffordAnderson** [comment]
@baskaufs Chinese, English, and Spanish videos ready for posting

**Comment by baskaufs** [comment]
Videos for 12 Gadgets are posted on YouTube with subtitles. But I will wait until I get a thumbs-up on the web layout before I generate any more Twine passages/web pages with the embedded videos.

**Comment by baskaufs** [comment]
Finished layout and video is embedded
