### ISSUE TITLE
13 relatedItems gadget

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#47]
Gadget that shows "derived statements" section at the bottom (statements that go in the inverse direction).

Created Box folder and stub English script

**Comment by baskaufs** [comment]
@CliffordAnderson @cylew @awesolek2 @Talinum @marjans74 The draft English script for 13 relatedItems gadgets is finished and in the Box folder.

**Comment by baskaufs** [comment]
@Talinum I made some edits to the `relatedItems` script talking about the "What links here" page. If you think the changes are OK, I'm done revising this script.

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese version animated

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish version animated

**Comment by awesolek2** [comment]
@CliffordAnderson English version recorded and animated.

**Comment by CliffordAnderson** [comment]
@baskaufs Chinese, English, and Spanish videos ready for posting

**Comment by baskaufs** [comment]
Video embedded and online
