### ISSUE TITLE
14 merge gadget

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#48]
There are two ways to merge. Need to figure out if the easiest one to use is the gadget or the "native" way.

Created Box folder and stub English script

**Comment by baskaufs** [comment]
Use the query to find duplicate people by locating two items with the same ORCID:

```
select distinct ?person1 ?person2 ?orcid where {
  ?person1 wdt:P496 ?orcid.
  ?person2 wdt:P496 ?orcid.
  filter(?person1 != ?person2)
  }
order by ?orcid
limit 10
```

**Comment by baskaufs** [comment]
@CliffordAnderson @marjans74 @awesolek2 @Talinum @cylew The 14 "merge gadget" draft English script is completed and is in the Box folder.

**Comment by baskaufs** [comment]
@Talinum I have spent about 10 minutes doing Google searches trying unsuccessfully to figure out where to go to request items to be merged. Can you direct me to some page with information on that service?

**Comment by baskaufs** [comment]
OK, I've communicated with @Talinum and it seems too complicated to extend the current script. So I'm considering this script finalized.

For the record, here are some of the resources Greg shared with me:

Method of tagging by adding instance of duplicate item with qualifier giving the identity of the duplicate: https://www.wikidata.org/wiki/Wikidata:Database_reports/Identified_duplicates

Talk page where some people have just requested someone else to do the merge (but this doesn't seem to be an official thing): 
https://www.wikidata.org/wiki/Help_talk:Merge

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese version (one of two) animated

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese version (two of two) animated

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish version animated

**Comment by awesolek2** [comment]
@CliffordAnderson English version recorded and animated

**Comment by CliffordAnderson** [comment]
@baskaufs Chinese, English, and Spanish videos are ready to go.
