### ISSUE TITLE
15 Identifiers for books

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#49]
Property for properties indicating notability:
< https://www.wikidata.org/wiki/Q62589316>

**Comment by baskaufs** [comment]
After talking with Charlotte, we decided that the way to go on this one was to cover using WorldCat to look up ISBN and WorldCat identifiers for a book. ISSNs for journals would be more complicated due to required qualifiers and many journals will already have items.

**Comment by baskaufs** [comment]
@CliffordAnderson @cylew @Talinum @marjans74 @awesolek2 I am stuck on the 15 IDs for books script because of complexities in formatting the identifier. At the meeting this afternoon, I want to talk about the tradeoff between depending on a bot to fix "bad" entries and how when a topic becomes too complicated or annoying to include in the video series.

**Comment by baskaufs** [comment]
@cylew @awesolek2 @Talinum  I am going to call 15 Identifiers for Books done. I am really not happy with it, but I'm not sure that it's fixable. If any of you think what I've written can be improved, I can try to change it, but I'm already past deadline on it and there would be a danger that someone has started translating prior to additional edits. So probably we should just use it unless someone strongly objects.

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese version animated

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish Version Animated.

**Comment by CliffordAnderson** [comment]
@baskaufs Chinese, English, and Spanish videos ready

**Comment by baskaufs** [comment]
Videos uploaded and embedded in the Twine
