### ISSUE TITLE
16 Identifiers for people

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#50]
After discussing with Charlotte, we decided that due to difficulties that some people have with finding people in ORCID using Chinese characters that it would be better to focus on VIAF identifiers for book authors. That's also less subject area specific than ORCID tends to be.

**Comment by baskaufs** [comment]
@CliffordAnderson @cylew @awesolek2 @marjans74 @Talinum The draft people identifiers script is in the Box folder and ready for review. Currently stuck on the books identifier script...

**Comment by baskaufs** [comment]
Comment from @Talinum 

Regarding #7 in the script 16 on people identifiers, I want to pass this along from the WD help pages.
(However, as a layman I would only use common names of plants as aliases, and scientific names as labels.)
 
Greg
---------------------------------------------------------------------
 
https://www.wikidata.org/wiki/Help:Label
 
Reflect common usage[editar]
Because the aim is to use the name that an item would be known by to the most readers, labels should reflect common usage. When it comes to scientific names, for example, of a species, labels should use a species' common name, however items must always also have the scientific name listed as Alias. If a species has several common names, a reasonable effort should be made to determine which of them is the most commonly used, e.g. by consulting references. The other names should be placed in the alias field along with the scientific name. If a species does not have a common name, the scientific name can be used as the label. Note that individual breeds do not have scientific names. Every breed of dog, from the Siberian Husky to the Chihuahua, is part of the species Canis lupus familiaris.
Examples:
The label of girasol (Q171497) is the common name, while the scientific name (Helianthus annuus) is featured as an alias.
Multiple common names exist for fútbol (Q2736). The most common name is picked for the label while the other ones are listed as aliases.

**Comment by baskaufs** [comment]
@Talinum Not sure if I understand this comment. Are you suggesting "David Michelson" as the label and "David Allen Michelson" as the alias? It isn't clear to me which is the name by which he is most commonly known professionally. I was assuming with the middle name since that's in VIAF, but maybe I'm wrong.

**Comment by baskaufs** [comment]
I made some small changes to the section about Dave M.'s middle name based on our discussion yesterday.

**Comment by baskaufs** [comment]
Oops, I forgot that I was going to move some text into this one, so it isn't done yet.

**Comment by baskaufs** [comment]
@Talinum @awesolek2 @cylew I guess the script for 16 Identifiers for people is done. I moved the introductory text about identifiers into it from 15, which is longer. We can introduce them in the lessons out of order (16 first, then 15).

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish version animated

**Comment by awesolek2** [comment]
@CliffordAnderson Looks like I already animated the Chinese version, but forgot to comment here!

**Comment by awesolek2** [comment]
@CliffordAnderson Scratch that. I mixed up 15 and 16. Both Spanish and Chinese are complete for 15. I will repost when I have done the same for 16.

**Comment by awesolek2** [comment]
@CliffordAnderson OK, both versions animated and uploaded.

**Comment by awesolek2** [comment]
@cylew paragraph 3 of the script contains some Chinese characters I am unsure of. Could you translate to English?

**Comment by cylew** [comment]
@awesolek2 The Chinese text was misplaced and thus removed.

**Comment by CliffordAnderson** [comment]
@baskaufs videos for Chinese and Spanish are ready. @awesolek2 , let me know when you have the English files up.

**Comment by awesolek2** [comment]
@CliffordAnderson English Version recorded and animated.

**Comment by CliffordAnderson** [comment]
@baskaufs English video ready

**Comment by baskaufs** [comment]
People Identifiers videos embedded in Twine
