### ISSUE TITLE
19 Intro

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#52]
Created Box folder and stub outline

**Comment by baskaufs** [comment]
@CliffordAnderson @marjans74 @cylew @awesolek2 I have created an outline for the intro based on @Talinum's existing introductory scripts. It is in the `19 Intro` box folder in the Script subfolder.

**Comment by baskaufs** [comment]
@CliffordAnderson @marjans74 @cylew @awesolek2  I have put into the Box folder 19 a draft of an intro that I built off of @Talinum's first two scripts. I feel like it's too long and I'm not feeling very good about the ordering of the content. Please take a look and we can talk about it at the meeting.

**Comment by baskaufs** [comment]
@CliffordAnderson @marjans74 @cylew @awesolek2 @Talinum I have cleaned up the script for 19 Intro (intro.docx): deleting extraneous information and making a few of the changes @Talinum suggested. The original copy had Chinese translations in it, so I spun that off as a separate document `intro_with_chinese.docx`.

**Comment by cylew** [comment]
Steve，
Thanks for removing the Chinese translations. I didn't realize that the word document is automatically save. 
Live and learn.

**Comment by baskaufs** [comment]
@cylew I think if you are using Box synch (where the Box folder on your local drive is synched to the cloud), the changes you make locally get pushed to the cloud every time you click save. That might be different from using Microsoft OneDrive. I think when you have a document open in OneDrive, it may be synching continuously with the cloud (like a Google Doc) and not just when you click save . But I can't remember for sure.

**Comment by cylew** [comment]
I didn't recall I saved the document and thus was surprised to know you spotted my translations. I prefer to open word documents on my desktop. When I tried that route, I was asked to contact for help because the old Box tools was not able to be removed for the installation of the new Box tools. I'm now confused if I should contact VUIT or LTDS.

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish Version animated

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese Version Animated

**Comment by awesolek2** [comment]
@CliffordAnderson English version recorded and animated.

**Comment by CliffordAnderson** [comment]
@baskaufs Chinese, English, and Spanish videos ready to go

**Comment by baskaufs** [comment]
Intro videos embedded

**Comment by awesolek2** [comment]
@CliffordAnderson French version animated.
