### ISSUE TITLE
20 Outro

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#53]
Created Box folder and stub outline

**Comment by baskaufs** [comment]
@Talinum @CliffordAnderson @marjans74 @cylew @awesolek2 The draft of the outro script is in Box folder 20.

**Comment by baskaufs** [comment]
@Talinum @CliffordAnderson @marjans74 @cylew @awesolek2 The outro script 20 has been cleaned up and is `outro.docx`. The previous copy with links, etc. is now called `outro_with_extraneous_junk.docx`.

**Comment by awesolek2** [comment]
@CliffordAnderson Chinese version animated.

**Comment by awesolek2** [comment]
@CliffordAnderson Spanish version animated

**Comment by awesolek2** [comment]
@CliffordAnderson English version recorded and animated!

**Comment by CliffordAnderson** [comment]
@baskaufs Chinese, English, and Spanish videos ready

**Comment by baskaufs** [comment]
Videos embedded for outro.

@CliffordAnderson For some reason, the outro in English and Spanish (not Chinese) has black, empty screen from about 1:19 to 4:59. In the interest of having something to look at, I went ahead and posted them, but this should be trimmed and re-uploaded before we wrap the project.

**Comment by CliffordAnderson** [comment]
@baskaufs Looks like something strange happened on export because the robot is also missing. I'll cut these again today.

**Comment by CliffordAnderson** [comment]
@baskaufs I recut the videos and upload new versions to Box.

**Comment by baskaufs** [comment]
Updated videos are now embedded.
