### ISSUE TITLE
non-English buttons need labels in the target languages

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#59]

**Comment by baskaufs** [comment]
@Talinum @cylew I have created an Excel file called `wikicite_labels.xlsx` that is in the root Box folder for the project. It has a list of labels that I need to have translated in order to change the button labels from English to the target language. In some cases, I'm not 100% sure that the English label text is the best, so if you have suggestions for better text, please feel to suggest changes.

There is still some uncertainty in my mind about how we should actually be linking some of the passages, particularly "help" and the outro, as well as the terminal branches (gadget, identifier, and subject paths). Hopefully, we can talk about it at the meeting today.

**Comment by Talinum** [comment]
@baskaufs  @cylew ...Steve, columns A and B get out of sync somewhere around Line 9.

**Comment by baskaufs** [comment]
Don't worry about column A. Those are a note to me of the pages on which the buttons are to be placed. The only thing that really matters is the translation of the actual labels that are in column B.

**Comment by Talinum** [comment]
@baskaufs  Good, that's what I'm doing.

**Comment by Talinum** [comment]
@baskaufs Spanish labels are ready.

**Comment by cylew** [comment]
@baskaufs 
Do the labels on the buttons need to be identical with the short titles for Youtube and title screen?
BTW, do we need to have a button for the Introduction? It's not listed on the spreadsheet in the label column.

**Comment by baskaufs** [comment]
@cylew no, they don't need to be identical. I think I abbreviated some of them and also some that lead to broader categories, like "identifiers" are more general, even though the page they lead to is more specific (like identifiers for books). You can just use your best judgement about something short that will make sense for a button that leads to a particular video.

I think there is no button for introduction because it's the first page. Otherwise one gets to it by "start over" which is on every page.

I hope this makes sense.

**Comment by baskaufs** [comment]
Button labels changed to Spanish and Chinese (except help and outro). @cylew @Talinum this involved a lot of manual copying and pasting, so there are undoubtedly errors that will need to be fixed. So running through the series and looking for mistakes would be good.

**Comment by Talinum** [comment]
@baskaufs @cylew The buttons for the outro are still in English, and there is a button that says "Volver al start over."
At the bottom of every page there are links "For futher information" in English.

Otherwise, looking good!

**Comment by baskaufs** [comment]
@Talinum Thanks for the proofreading! The links at the bottom are template data for the unstarted Issue #64 (finish reference section). The outro buttons (and help buttons) aren't done because I'm not really sure how they ultimately will fit in the flow of the website (see issue #61). I'm going to go ahead and close this since those unresolved things are still in open issues.
