### ISSUE TITLE
Check first two TLDR in Chinese for 3 Author 添加作者

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#60]
learning-objectives.docx has:

•	作者的陈述可以是有链接的，也可以是没有链接的作者名称字符。
•	用搜索空栏来找寻项目进而确认它是否已经收录在维基数据里。在搜索时，若项目有别名，一定也要搜索别名。

The current text in the website has:
用搜索空栏来找寻项目进而确认它是否已经收录在维基数据里。
在搜索时，若项目有别名，一定也要搜索别名。

The third TLDR is the same both places. Which should be used?

**Comment by cylew** [comment]
Steve,

Please use the text listed in learning-objectives.docx.
• 作者的陈述可以是有链接的，也可以是没有链接的作者名称字符。
• 用搜索空栏来找寻项进而确认它是否已经收录在维基数据里。在搜索时，若项有别名，一定也要搜索别名。

Thanks much,
Charlotte
