### ISSUE TITLE
Flow control questions for website

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#61]
@CliffordAnderson @Talinum @cylew @awesolek2 @marjans74 I would like to address the following questions at our May 13 call:

1. Is the flow/topology represented in the diagram on the [landing page](https://github.com/HeardLibrary/twine-for-wikicite) what we want?
2. Where does a "get help" link belong? Linked at the bottom of every page?
3. How do we access the outro? What is its relationship (if any) to the quit page?

**Comment by baskaufs** [comment]
1. People were OK with the current branches.
2. Try to make the "get help" link to show up on the sidebar.
3. Put the outro at the bottom of each page and also below the video at the branch tips.

**Comment by baskaufs** [comment]
I have made the "quit" link at the bottom of each page point to the outro and deleted the "quit" passage, which didn't actually do anything. The buttons below the video at the ends of the path branches are actually entitled "next steps" rather than "quit", even though they point to the same page.

Because the "quit" button leads to the outro from every page (including the first ones), I changed the page title from "Congratulations for finishing the lessons!" to "Where do I go from here?" which seemed more appropriate. But I can change it back to something more congratulatory if people like that better. It just shouldn't say "... for finishing the lessons". I'm open to suggestions.

**Comment by marjans74** [comment]
That sounds like a great solution Steve.  Maybe compromise with Congratulations on finishing that lesson.  Where can I go from here?

**Comment by cylew** [comment]
@baskaufs @Talinum 
I tested the navigation of the lessons in Chinese and spotted some issues:
no start over button included in the Intro lesson under more information
no edit article button listed in the Edit Book lesson and no option available to move to the next lesson
no add item button listed in the Edit Article lesson, which interrupts the continuity of the lessons
I also browsed the navigation of the lessons in English, it works smoothly. Please make sure that pattern is mirrored to the passage of the lessons in Chinese.
Could we consider listing the 20 lessons under Learn Wikidata in the sidebar so the users can have an overview of the tutorials, which can help facilitate their self-paced learning?

**Comment by baskaufs** [comment]
@cylew Thanks for the proofreading!

The "Start over" button links to the Intro page, so putting it on the intro page would just send the user to the same page they were already on. So that's why it isn't there.

The reason the Book lesson doesn't have a link to the Article lesson is that they are parallel lessons that have the same learning objectives. So in theory, the user could go on either path (account->Book->add_item or account->Article->add_item) without taking the other path. I don't know if that is the best way or not, but it's how the navigation originally was and I didn't change it. It is the same in all of the language versions, so if we want to change it to something else, all versions will all need to be changed.

I am confused when you say there is no Add_item button in the edit Article. It has the button with "创建新项", which Google Translate says is "Create new item" and it goes to the 创建新项 page. Does that page have the wrong video or something?

As far as I know, all of the language versions follow this same path:

![](https://raw.githubusercontent.com/HeardLibrary/twine-for-wikicite/main/map.png)

I clicked through all of them when I finished adding the button labels, but it is difficult for me to make sure that the Chinese ones are correct once I changed them from English. They were correctly linked when the button labels were still in English, and the links should not have changed when I changed the labels. But I could easily have pasted in the wrong labels somewhere.

We definitely should try to add the lessons to the sidebar if somebody can figure out how to do it.

**Comment by baskaufs** [comment]
OK, the sidebar is easy: https://twinery.org/forum/discussion/8679/how-do-i-edit-the-sidebar-in-sugarcube

I'll try to whip something up there.

**Comment by baskaufs** [comment]
@CliffordAnderson @awesolek2 @marjans74 @cylew @Talinum Sidebar is done in all languages. Check it for errors or changes. When the potential Chinese links issues are resolved, this issue can be closed.

**Comment by cylew** [comment]
@baskaufs I tested sidebar in Chinese and all the links work.
Before you closed the ticket, I have a question about the Outro lesson. Sorry, if it is not related to the assigned ticket. Should we include some links mentioned in the lesson in "For further Information" such as the landing page of our project and/or the Communication page of the Practical Wikidata for the Librarians?

**Comment by baskaufs** [comment]
@cylew Definitely we need those kinds of links. I am going to go ahead and close this ticket since your question relates to Issue #64 and I've started on that now.
