### ISSUE TITLE
Finish the reference sections after TLDR

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#64]
I forgot that this still hasn't been done. What is there now is just template data.

**Comment by baskaufs** [comment]
@Talinum @cylew @awesolek2 @CliffordAnderson @marjans74 I have started on this with book_identifiers, people_identifiers, classification, getting_help, and outro. But I need references for other passages/pages and also translations of the links and of "For further information:".

**Comment by baskaufs** [comment]
Alright, I think I've added all of the en, es, and zh references. I proofread them and caught a lot of copy/paste errors and I made sure that all of the links worked. But probably still needs to be checked by @Talinum and @cylew to make sure I didn't make any silly copying mistakes.

**Comment by cylew** [comment]
@baskaufs Please unitalicize "OLCL" and "WorldCat" in the Identifiers for Books。
It should be "ISBN国际标准书号和OCLC控制号可从WorldCat世界图书馆目录检索平台获得。 "

**Comment by baskaufs** [comment]
Should be fixed now @clew
