### ISSUE TITLE
We need a credits page

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/twine-for-wikicite#66]
Single link on the sidebar.

**Comment by awesolek2** [comment]
Andrew Wesolek, Robot animations and voice for English version

**Comment by baskaufs** [comment]
@CliffordAnderson, when you talk to the grantors, can you please ask what language they would like to have on this page for their funding?

Also, @CliffordAnderson @awesolek2  all of the videos have CC BY licenses (the default, I left it there) but what kind of use/licensing information do we need to provide on the website, and where? We should have something to make it clear how it can be reused.

**Comment by baskaufs** [comment]
Steve Baskauf (username: baskaufs) - script-writing, Twine programming, web content, video metadata management

**Comment by cylew** [comment]
Charlotte Lew - curriculum design, Chinese translation and localization, and Chinese narration

**Comment by baskaufs** [comment]
I'm putting together the credits page and have several questions for each person:

1. Do you want your Wikimedia username included with your information?
2. If you want your Wikimedia username included, do you want it linked to your userpage?
3. Do you want your real name included? If you are averse to exposure on the Internet, including only your Wikimedia username would be in keeping with community practices in the Wiki world.
4. If you want your real name included, do you want it hyperlinked to any particular web page (like your homepage or CV if you have one)

**Comment by CliffordAnderson** [comment]
My details:

[Clifford Anderson](https://www.cliffordanderson.net/) ([User: CliffordAnderson](https://en.wikipedia.org/wiki/User:Clifford_Anderson)), project management and video production

Thanks!

**Comment by baskaufs** [comment]
Oh, @Talinum @cylew I need translated text for "Credits" and "Contributors" in es and zh-Hans

**Comment by cylew** [comment]
@baskaufs @Talinum 
Depends on how to contextualize "credits". If you tend to say pay "credits" where they are due, it should be “荣誉”。 If you phrase it as "credits page", it should be "致谢页“。
"Contributors" is easier, "贡献者”。Does this help?

**Comment by cylew** [comment]
@baskaufs I don't have any preference if my Wikimedia username is included or not. I will follow the practice with the rest of the team members. My username is Charlotte Y. Lew. As you can tell, my username is my real name. And Q104738269 is my ID. Hopefully the name exposure won't cause me too much of trouble. Let me know if you need further information.

**Comment by baskaufs** [comment]
@cylew I went ahead and added your username. I don't think it should be a problem. I also put in the page title and link, but realized that we probably need to translate our roles into all of the languages, too. But there is no point in working on that until we have the info from everyone. 

You can see what I've done so far by going to the bottom of the sidebar and clicking on the link. The credit page doesn't have any styling right now.

**Comment by cylew** [comment]
@baskaufs Thanks for your help. I agree we should translate our roles into the languages we offer.
I had a conversation with Greg this morning and we both hope that you could extend your work time as a 12 month term so we don't feel guilty to send you any inquiries in the summer. Whatever you've contributed during your time off is much more appreciated.

**Comment by Talinum** [comment]
English and Spanish credits are caught up, but still need @marjans74 and Susan to submit. Marymae, feel free to copy from the English credits. 
Filenames in Box root directory are "Credits" and "Credits_Spanish"
They will need reordering reformatting when data is all in.

**Comment by baskaufs** [comment]
I put the existing credit info onto the page. So es and en are mostly done except for a few untranslated es words (@Talinum "Credits" link, stuff at bottom of page, which isn't finished anyway). 

@cylew Needs Chinese translations still I think.

@CliffordAnderson still wondering about how to credit the funding...

**Comment by CliffordAnderson** [comment]
@baskaufs For funding, let's write "[WikiCite](WikiCite is funded by the Alfred P. Sloan Foundation) is funded by the Alfred P. Sloan Foundation." Thanks!

**Comment by Talinum** [comment]
@baskaufs  
Please add to Charlotte's credits, "narración en chino"

credits page title:
Contribuyentes a Wikicite para Bibliotecólogos

Realizado con apoyo financiero de la Fundación Alfred P. Sloan

**Comment by marjans74** [comment]
I checked the credits document in BOX, and what is there for me is fine.  It's okay to use my real name.  Or, if everyone decides to use only their wikidate user name, that is fine with me.  Thanks,

**Comment by baskaufs** [comment]
@Talinum I changed the sidebar links from the placeholder "Credits" to "Creditos". Is that correct?

**Comment by Talinum** [comment]
@baskaufs I would prefer "Contribuyentes" for the link text.

I remembered too late about the link.

**Comment by cylew** [comment]
@baskaufs I just uploaded the Chinese credits page onto Box. @Talinum Did you add more items to Cliff's contributions list in Spanish? If so, please inform me what they are.

**Comment by baskaufs** [comment]
I think this is done enough that we can close this and catch any other issues during proofreading.
